(ns kontor.settlement
  "A book that lived in a speculative world settles into its parent by
   replay, never by datom merge (ADR-172).

   A world — a branch of the book an agent works in — is an autonomous book:
   it posts, numbers and reverses as the root does. When the parent takes it
   in, [[extract]] reads the world's NET effect since its base as intents,
   [[parent-claims]] what the parent did meanwhile, and [[stamp!]] re-posts
   the intents through the gate in the parent, which allocates fresh gapless
   numbers. Conflicts between worlds, or between a world and its parent, are
   decided by the caller (footprints), never by picking datoms.

   An intent:

     {:intent/id      origin uuid (`:kontor.transaction/origin-id`)
      :footprint      #{[:origin id] [:external-id caller-id] [:reverses eid] …}
      :effective-date inst
      :entry          `kontor.book` entry options that re-create the entry
      :reverses       eid of a base entry it reverses, or nil
      :actor          uid of who sealed it, or nil
      :world-number   the number it carried in the world, or nil}

   This slice replays posted journal entries (any `kontor.book` verb) and
   reversals. Anything else a world changed — a draft, an invoice, a new
   partner or account, a period close — is refused by [[extract]] with the
   entities named: silently carrying it over as datoms is exactly what this
   namespace exists to prevent."
  (:require [datahike.api :as d]
            [kontor.book :as book]
            [kontor.book.build :as build]
            [kontor.gate :as gate]
            [kontor.numbering :as numbering]
            [kontor.posting.build :as posting-build]))

;; ============================================================================
;; What a world changed
;; ============================================================================

(defn- world-datoms
  "Datoms `world-db` holds that `base-db` did not: those of transactions
   after the base's last one (a branch continues the base's history)."
  [base-db world-db]
  (let [since (:max-tx base-db)]
    (filter #(> (:tx %) since) (d/datoms world-db :eavt))))

(def ^:private carried-transaction-attrs
  "Transaction attributes a replay re-creates from the entry, or that the
   gate regenerates in the parent."
  #{:kontor.transaction/journal :kontor.transaction/effective-date
    :kontor.transaction/narration :kontor.transaction/partner
    :kontor.transaction/external-id :kontor.transaction/settles
    :kontor.transaction/reverses :kontor.transaction/origin-id
    ;; regenerated by the seal and the gate
    :kontor.transaction/state :kontor.transaction/posted-at
    :kontor.transaction/posted-by :kontor.transaction/sequence-number
    :kontor.transaction/sequence-key
    :kontor.audit/create-uid :kontor.audit/write-uid})

(def ^:private carried-posting-attrs
  "Posting attributes `kontor.book/entry-postings` re-creates."
  #{:kontor.posting/transaction :kontor.posting/posted-at
    :kontor.posting/account :kontor.posting/amount :kontor.posting/commodity
    :kontor.posting/partner :kontor.posting/entity :kontor.posting/ledger
    :kontor.posting/narration :kontor.posting/display-type
    :kontor.posting/period-tag :kontor.posting/dimensions
    :kontor.posting/analytic-distributions
    :kontor.audit/create-uid :kontor.audit/write-uid})

(defn- valid-time-attr? [a] (= "db.valid" (namespace a)))

(defn- entity-kind
  "What entity `e` is, from the attributes it has in `db`."
  [db e]
  (let [attrs (set (map :a (d/datoms db :eavt e)))
        has (fn [ns] (some #(= ns (namespace %)) attrs))]
    (cond
      (contains? attrs :kontor.transaction/journal) :transaction
      (contains? attrs :kontor.posting/transaction) :posting
      (has "kontor.posting-dimension") :posting-part
      (has "kontor.analytic-distribution") :posting-part
      (has "kontor.actor") :actor
      (contains? attrs :kontor.journal/code) :journal
      :else :other)))

(defn- existed? [db e] (boolean (seq (d/datoms db :eavt e))))

(defn- unsupported! [what details]
  (throw (ex-info (str "kontor.settlement: the world " what
                       " — this settlement cannot replay it, and carrying it"
                       " over as datoms would bypass the gate (ADR-172)")
                  (merge {:type ::unsupported} details))))

(defn- changed-entities
  "{eid #{attr}} of what the world changed, tx entities left out."
  [base-db world-db]
  (reduce (fn [m {:keys [e a tx]}]
            (if (or (= e tx) (= "db" (namespace a)))
              m
              (update m e (fnil conj #{}) a)))
          {}
          (world-datoms base-db world-db)))

(defn- check-changes!
  "Refuse any change this slice does not replay. Returns the ids of the
   new transactions."
  [base-db world-db changes]
  (let [counter-attrs #{:kontor.journal/last-sequence :kontor.journal/last-sequence-key}]
    (vec
     (keep
      (fn [[e attrs]]
        (let [kind (entity-kind world-db e)
              new? (not (existed? base-db e))
              attrs (remove valid-time-attr? attrs)]
          (case kind
            :transaction
            (let [unknown (remove carried-transaction-attrs attrs)
                  t (d/pull world-db [:kontor.transaction/posted-at] e)]
              (cond
                (not new?) (unsupported! "changed an entry of its base" {:entity e :attrs (vec attrs)})
                (seq unknown) (unsupported! "wrote transaction attributes a replay does not carry"
                                            {:entity e :attrs (vec unknown)})
                (not (:kontor.transaction/posted-at t)) (unsupported! "holds a draft entry" {:entity e})
                :else e))
            :posting
            (let [unknown (remove carried-posting-attrs attrs)]
              (when (or (not new?) (seq unknown))
                (unsupported! "wrote posting attributes a replay does not carry"
                              {:entity e :attrs (vec (if new? unknown attrs))}))
              nil)
            (:posting-part :actor) (when-not new? (unsupported! "changed an existing entity" {:entity e :kind kind :attrs (vec attrs)}))
            :journal (when (seq (remove counter-attrs attrs))
                       (unsupported! "changed a journal" {:entity e :attrs (vec attrs)}))
            (unsupported! "changed an entity of a kind it cannot replay"
                          {:entity e :kind kind :attrs (vec attrs)}))))
      changes))))

;; ============================================================================
;; Intents
;; ============================================================================

(defn- ref-id [x] (if (map? x) (:db/id x) x))

(defn- world-number
  "The number the numbering rendered for entry `t` in the world, or nil when
   its external-id is the caller's own."
  [db {:kontor.transaction/keys [external-id sequence-number journal effective-date]}]
  (when (and external-id sequence-number)
    (let [cfg (numbering/journal-config db (ref-id journal))]
      (when (= external-id (numbering/render cfg sequence-number effective-date))
        external-id))))

(defn- intent
  [world-db e]
  (let [t (d/pull world-db '[* {:kontor.transaction/posted-by [:kontor.actor/uid]}] e)
        rendered (world-number world-db t)
        caller-id (when-not rendered (:kontor.transaction/external-id t))
        reverses (ref-id (:kontor.transaction/reverses t))
        entry (cond-> {:journal (ref-id (:kontor.transaction/journal t))
                       :effective-date (:kontor.transaction/effective-date t)
                       :postings (book/entry-postings world-db e)}
                (:kontor.transaction/narration t) (assoc :narration (:kontor.transaction/narration t))
                (:kontor.transaction/partner t) (assoc :partner (ref-id (:kontor.transaction/partner t)))
                caller-id (assoc :external-id caller-id)
                (seq (:kontor.transaction/settles t))
                (assoc :settles (mapv ref-id (:kontor.transaction/settles t))))
        origin (:kontor.transaction/origin-id t)]
    {:intent/id origin
     :footprint (cond-> #{[:origin origin]}
                  caller-id (conj [:external-id caller-id])
                  reverses (conj [:reverses reverses]))
     :effective-date (:kontor.transaction/effective-date t)
     :entry entry
     :reverses reverses
     :actor (get-in t [:kontor.transaction/posted-by :kontor.actor/uid])
     :world-number rendered
     ::world-eid e}))

(defn- referenced-eids
  "Every entity id an intent's entry refers to."
  [{:keys [entry reverses]}]
  (->> (concat [(:journal entry) (:partner entry) reverses]
               (:settles entry)
               (mapcat (fn [p] (concat [(:account p) (:commodity p) (:partner p)
                                        (:entity p) (:ledger p)]
                                       (keep :plan (:analytic-distributions p))
                                       (keep :account (:analytic-distributions p))))
                       (:postings entry)))
       (filter integer?)
       distinct))

(defn extract
  "The world's net effect since its base, as intents (see the namespace):
   every entry it posted, except an entry it reversed itself — which is
   dropped together with its reversal. Throws `::unsupported` for anything
   else it changed, and `::new-reference` when an entry refers to an entity
   the world created (this slice replays against the base's entities)."
  [base-db world-db]
  (let [txs (check-changes! base-db world-db (changed-entities base-db world-db))
        intents (mapv #(intent world-db %) txs)
        in-world (set txs)
        self-reversed (set (mapcat (fn [{:keys [reverses] :as i}]
                                     (when (contains? in-world reverses)
                                       [reverses (::world-eid i)]))
                                   intents))
        kept (remove #(contains? self-reversed (::world-eid %)) intents)]
    (doseq [i kept
            e (referenced-eids i)
            :when (not (existed? base-db e))]
      (throw (ex-info "kontor.settlement: an entry refers to an entity the world created"
                      {:type ::new-reference :entity e :intent (:intent/id i)})))
    (vec (sort-by (juxt :effective-date #(str (:intent/id %))) kept))))

(defn parent-claims
  "The footprint keys the parent claimed since `base-db`: its own entries'
   origins, caller ids and the base entries it reversed. Unlike [[extract]]
   this reads whatever the parent did and refuses nothing."
  [base-db parent-db]
  (let [since (:max-tx base-db)
        txs (d/q '[:find [?t ...] :in $ ?since
                   :where [?t :kontor.transaction/posted-at _ ?tx] [(> ?tx ?since)]]
                 parent-db since)]
    (into #{}
          (mapcat (fn [e]
                    (let [t (d/pull parent-db '[*] e)
                          caller-id (when-not (world-number parent-db t)
                                      (:kontor.transaction/external-id t))]
                      (cond-> []
                        (:kontor.transaction/origin-id t) (conj [:origin (:kontor.transaction/origin-id t)])
                        caller-id (conj [:external-id caller-id])
                        (:kontor.transaction/reverses t)
                        (conj [:reverses (ref-id (:kontor.transaction/reverses t))])))))
          txs)))

;; ============================================================================
;; Stamping into the parent
;; ============================================================================

(defn stamp-tx-data
  "Pure-over-`db` tx-data that re-posts `intents` (in order) into the book
   `db` belongs to, skipping those whose origin it already holds. Each
   entry keeps its origin; the gate allocates its number."
  [db intents]
  (vec
   (mapcat
    (fn [{:intent/keys [id] :keys [entry reverses actor]}]
      (when-not (d/entity db [:kontor.transaction/origin-id id])
        (let [tempid (str "settle-" id)
              input (assoc (build/build-input entry) :tx-tempid tempid)
              tx-data (posting-build/post-transaction-tx-data
                       input (cond-> {} actor (assoc :actor actor)))]
          (mapv (fn [form]
                  (if (and (map? form) (= tempid (:db/id form)))
                    (cond-> (assoc form :kontor.transaction/origin-id id)
                      reverses (assoc :kontor.transaction/reverses reverses))
                    form))
                tx-data))))
    intents)))

(defn stamp!
  "Re-post `intents` into `conn`'s book through the gate, as ONE transaction:
   the parent numbers them consecutively, and a refused intent (a locked
   period, a closed sequence bucket) refuses them all. Intents the book
   already holds (by origin) are skipped, so a retry books nothing twice.
   Returns {world-number parent-number} for the entries that carried a
   rendered number in the world."
  [conn intents]
  (let [tx-data (stamp-tx-data (d/db conn) intents)]
    (when (seq tx-data)
      (gate/transact-with-validation conn tx-data))
    (let [db (d/db conn)]
      (into {}
            (keep (fn [{:intent/keys [id] :keys [world-number]}]
                    (when world-number
                      [world-number (:kontor.transaction/external-id
                                     (d/entity db [:kontor.transaction/origin-id id]))])))
            intents))))
