(ns kontor.settlement
  "A book that lived in a speculative world settles into its parent by
   replay, never by datom merge (ADR-172).

   A world — a branch of the book an agent works in — is an autonomous book:
   it posts, numbers and reverses as the root does. When the parent takes it
   in, [[extract]] reads the world's NET effect since its base as intents,
   [[parent-claims]] what the parent did meanwhile, and [[stamp!]] re-posts
   the intents through the gate in the parent, which allocates fresh gapless
   numbers. Conflicts between worlds, or between a world and its parent, are
   decided by the caller (footprints), never by picking datoms.

   An intent:

     {:intent/id      origin uuid (`:kontor.transaction/origin-id`)
      :footprint      #{[:origin id] [:external-id caller-id] [:reverses eid] …}
      :effective-date inst
      :entry          `kontor.book` entry options that re-create the entry
      :reverses       eid of a base entry it reverses, or nil
      :actor          uid of who sealed it, or nil
      :world-number   the number it carried in the world, or nil}

   Replayed: posted journal entries (any `kontor.book` verb), reversals, and
   invoices the world created — as drafts, or sent, in which case the replay
   links them to their replayed posting and the gate gives them the parent's
   gapless `:kontor.invoice/number` (an invoice intent's footprint is
   `[:invoice external-id]`); bank lines it imported and its bank matches,
   replayed as match decisions against the parent's state (footprint
   `[:bank-line id]`); and reference data it created (partners, accounts,
   commodities, ledgers, journals, …), replayed by identity and referred to
   by it. Anything else a world changed — a draft entry, an invoice
   cancelled, a period close, an outbox intent — is refused by [[extract]]
   with the entities named: silently carrying it over as datoms is exactly
   what this namespace exists to prevent."
  (:require [clojure.string :as str]
            [datahike.api :as d]
            [kontor.book :as book]
            [kontor.book.build :as build]
            [kontor.banking.reconciliation :as recon]
            [kontor.compliance.period :as period]
            [kontor.document.invoice :as invoice]
            [kontor.workflow.status-machine :as sm]
            [kontor.gate :as gate]
            [kontor.numbering :as numbering]
            [kontor.posting.build :as posting-build]))

;; ============================================================================
;; What a world changed
;; ============================================================================

(defn- world-datoms
  "Datoms `world-db` holds that `base-db` did not: those of transactions
   after the base's last one (a branch continues the base's history)."
  [base-db world-db]
  (let [since (:max-tx base-db)]
    (filter #(> (:tx %) since) (d/datoms world-db :eavt))))

(def ^:private carried-transaction-attrs
  "Transaction attributes a replay re-creates from the entry, or that the
   gate regenerates in the parent."
  #{:kontor.transaction/journal :kontor.transaction/effective-date
    :kontor.transaction/narration :kontor.transaction/partner
    :kontor.transaction/external-id :kontor.transaction/settles
    :kontor.transaction/reverses :kontor.transaction/origin-id
    ;; regenerated by the seal and the gate
    :kontor.transaction/state :kontor.transaction/posted-at
    :kontor.transaction/posted-by :kontor.transaction/sequence-number
    :kontor.transaction/sequence-key
    :kontor.audit/create-uid :kontor.audit/write-uid})

(def ^:private carried-posting-attrs
  "Posting attributes `kontor.book/entry-postings` re-creates."
  #{:kontor.posting/transaction :kontor.posting/posted-at
    :kontor.posting/account :kontor.posting/amount :kontor.posting/commodity
    :kontor.posting/partner :kontor.posting/entity :kontor.posting/ledger
    :kontor.posting/narration :kontor.posting/display-type
    :kontor.posting/period-tag :kontor.posting/dimensions
    :kontor.posting/analytic-distributions
    :kontor.audit/create-uid :kontor.audit/write-uid})

(defn- valid-time-attr? [a] (= "db.valid" (namespace a)))

(def ^:private catalog-identities
  "Kinds of reference data a world may create, by their identity attribute:
   replayed by identity (created in the parent, or recognized there), and
   referred to by it. Document-like kinds with an identity — an outbox
   intent, a saga step, a legal hold — are deliberately not catalog data."
  [:kontor.partner/external-id :kontor.account/path :kontor.commodity/symbol
   :kontor.ledger/code :kontor.analytic-account/path :kontor.payment-term/code
   :kontor.journal/code])

(defn- catalog-identity
  "[identity-attr value] of catalog entity `e` in `db`, or nil."
  [db e]
  (some (fn [a] (when-let [v (a (d/entity db e))] [a v])) catalog-identities))

(defn- entity-kind
  "What entity `e` is, from the attributes it has in `db`."
  [db e]
  (let [attrs (set (map :a (d/datoms db :eavt e)))
        has (fn [ns] (some #(= ns (namespace %)) attrs))]
    (cond
      (contains? attrs :kontor.transaction/journal) :transaction
      (contains? attrs :kontor.invoice/external-id) :invoice
      (contains? attrs :kontor.bank-line/external-id) :bank-line
      (has "kontor.payment-application") :payment-application
      (has "kontor.invoice-line") :invoice-line
      (has "kontor.status-history") :status-history
      (contains? attrs :kontor.posting/transaction) :posting
      (has "kontor.posting-dimension") :posting-part
      (has "kontor.analytic-distribution") :posting-part
      (has "kontor.actor") :actor
      (has "kontor.period") :period
      (contains? attrs :kontor.side-effect-intent/key) :outbox
      (contains? attrs :kontor.journal/code) :journal
      (catalog-identity db e) :catalog
      :else :other)))

(defn- existed? [db e] (boolean (seq (d/datoms db :eavt e))))

(defn- unsupported! [what details]
  (throw (ex-info (str "kontor.settlement: the world " what
                       " — this settlement cannot replay it, and carrying it"
                       " over as datoms would bypass the gate (ADR-172)")
                  (merge {:type ::unsupported} details))))

(defn- changed-entities
  "{eid #{attr}} of what the world changed, tx entities left out."
  [base-db world-db]
  (reduce (fn [m {:keys [e a tx]}]
            (if (or (= e tx) (= "db" (namespace a)))
              m
              (update m e (fnil conj #{}) a)))
          {}
          (world-datoms base-db world-db)))

(def ^:private replayed-invoice-statuses
  "`:paid` only when a replayed match settles it: the invoice replays as
   sent, and the match re-derives its status in the parent."
  #{:draft :sent :paid})

(defn- check-changes!
  "Refuse any change this slice does not replay. Returns {:transactions
   [eid] :invoices [eid]}, the new ones."
  [base-db world-db changes]
  (let [counter-attrs #{:kontor.journal/last-sequence :kontor.journal/last-sequence-key}]
    (group-by first
              (keep
               (fn [[e attrs]]
                 (let [kind (entity-kind world-db e)
                       new? (not (existed? base-db e))
                       attrs (remove valid-time-attr? attrs)]
                   (case kind
                     :transaction
                     (let [unknown (remove carried-transaction-attrs attrs)
                           t (d/pull world-db [:kontor.transaction/posted-at] e)]
                       (cond
                         (not new?) (unsupported! "changed an entry of its base" {:entity e :attrs (vec attrs)})
                         (seq unknown) (unsupported! "wrote transaction attributes a replay does not carry"
                                                     {:entity e :attrs (vec unknown)})
                         (not (:kontor.transaction/posted-at t)) (unsupported! "holds a draft entry" {:entity e})
                         :else [:transactions e]))
                     :invoice
                     (let [status (:kontor.invoice/status (d/pull world-db [:kontor.invoice/status] e))]
                       (cond
                         ;; a match settling it re-derives its status in the
                         ;; parent; anything else is checked in `extract`
                         (and (not new?) (every? #{:kontor.invoice/status} attrs))
                         [:invoice-statuses e]
                         (not new?) (unsupported! "changed an invoice of its base" {:entity e :attrs (vec attrs)})
                         (not (replayed-invoice-statuses status))
                         (unsupported! "holds an invoice in a status this settlement cannot replay"
                                       {:entity e :status status})
                         :else [:invoices e]))
                     :bank-line
                     (if (or new? (every? #{:kontor.bank-line/status :kontor.bank-line/reconciled-at
                                            :kontor.bank-line/posting}
                                          attrs))
                       [:bank-lines e]
                       (unsupported! "changed a bank line beyond matching it" {:entity e :attrs (vec attrs)}))
                     ;; regenerated when the match is replayed
                     :payment-application
                     (when-not new? (unsupported! "changed a payment application" {:entity e}))
                     :invoice-line (when-not new? (unsupported! "changed an invoice line of its base" {:entity e :attrs (vec attrs)}))
            ;; regenerated by the replay's own status changes
                     :status-history (when-not new? (unsupported! "changed a status history row" {:entity e}))
                     :posting
                     (let [unknown (remove carried-posting-attrs attrs)]
                       (when (or (not new?) (seq unknown))
                         (unsupported! "wrote posting attributes a replay does not carry"
                                       {:entity e :attrs (vec (if new? unknown attrs))}))
                       nil)
                     (:posting-part :actor) (when-not new? (unsupported! "changed an existing entity" {:entity e :kind kind :attrs (vec attrs)}))
                     :journal (cond
                                new? [:catalog e]
                                (seq (remove counter-attrs attrs))
                                (unsupported! "changed a journal" {:entity e :attrs (vec attrs)}))
                     :period
                     (if (and (not new?)
                              (every? #{:kontor.period/locked-at :kontor.period/lock-tx
                                        :kontor.period/sealed-at :kontor.period/sealed-by}
                                      attrs))
                       [:periods e]
                       (unsupported! (if new? "created a period" "changed a period beyond closing it")
                                     {:entity e :attrs (vec attrs)}))
                     :outbox
                     (let [status (:kontor.side-effect-intent/status (d/entity world-db e))]
                       (cond
                         (not new?) (unsupported! "worked an outbox intent of its base: an external effect left a speculative world" {:entity e})
                         (not= :pending status)
                         (unsupported! "ran an outbox intent: an external effect left a speculative world"
                                       {:entity e :status status})
                         :else [:outbox e]))
                     :catalog (if new?
                                [:catalog e]
                                (unsupported! "changed reference data of its base"
                                              {:entity e :identity (catalog-identity world-db e)
                                               :attrs (vec attrs)}))
                     (unsupported! "changed an entity of a kind it cannot replay"
                                   {:entity e :kind kind :attrs (vec attrs)}))))
               changes))))

(defn- ids-of [grouped k] (mapv second (get grouped k)))

;; ============================================================================
;; Intents
;; ============================================================================

(defn- ref-id [x] (if (map? x) (:db/id x) x))

(defn- world-number
  "The number the numbering rendered for entry `t` in the world, or nil when
   its external-id is the caller's own."
  [db {:kontor.transaction/keys [external-id sequence-number journal effective-date]}]
  (when (and external-id sequence-number)
    (let [cfg (numbering/journal-config db (ref-id journal))]
      (when (= external-id (numbering/render cfg sequence-number effective-date))
        external-id))))

(defn- intent
  [world-db e]
  (let [t (d/pull world-db '[* {:kontor.transaction/posted-by [:kontor.actor/uid]}] e)
        rendered (world-number world-db t)
        caller-id (when-not rendered (:kontor.transaction/external-id t))
        reverses (ref-id (:kontor.transaction/reverses t))
        entry (cond-> {:journal (ref-id (:kontor.transaction/journal t))
                       :effective-date (:kontor.transaction/effective-date t)
                       :postings (book/entry-postings world-db e)}
                (:kontor.transaction/narration t) (assoc :narration (:kontor.transaction/narration t))
                (:kontor.transaction/partner t) (assoc :partner (ref-id (:kontor.transaction/partner t)))
                caller-id (assoc :external-id caller-id)
                (seq (:kontor.transaction/settles t))
                (assoc :settles (mapv ref-id (:kontor.transaction/settles t))))
        origin (:kontor.transaction/origin-id t)]
    {:intent/id origin
     :kind :entry
     :footprint (cond-> #{[:origin origin]}
                  caller-id (conj [:external-id caller-id])
                  reverses (conj [:reverses reverses]))
     :effective-date (:kontor.transaction/effective-date t)
     :entry entry
     :reverses reverses
     :actor (get-in t [:kontor.transaction/posted-by :kontor.actor/uid])
     :world-number rendered
     ::world-eid e}))

(defn- plain
  "A pulled entity as data for re-creation: refs as eids, without the
   attributes in `drop`."
  [m drop]
  (into {} (keep (fn [[k v]]
                   (when-not (contains? drop k)
                     [k (cond (map? v) (:db/id v)
                              (and (coll? v) (map? (first v))) (mapv :db/id v)
                              :else v)])))
        (dissoc m :db/id)))

(defn- invoice-intent
  [world-db e]
  (let [inv (d/pull world-db '[* {:kontor.invoice/lines [*]}] e)
        ext (:kontor.invoice/external-id inv)
        origin (some->> (:kontor.invoice/transaction inv) ref-id
                        (d/entity world-db) :kontor.transaction/origin-id)]
    {:intent/id (str "invoice:" ext)
     :kind :invoice
     :footprint #{[:invoice ext]}
     :effective-date (:kontor.invoice/issue-date inv)
     :invoice (plain inv #{:kontor.invoice/lines :kontor.invoice/transaction
                           :kontor.invoice/status :kontor.invoice/number})
     :lines (mapv #(plain % #{:kontor.invoice-line/invoice})
                  (sort-by :kontor.invoice-line/sequence (:kontor.invoice/lines inv)))
     ;; a paid one replays as sent: its match re-derives the rest
     :status (if (= :paid (:kontor.invoice/status inv)) :sent (:kontor.invoice/status inv))
     :transaction-origin origin
     :world-number (:kontor.invoice/number inv)}))

(defn- ref-values [m] (filter integer? (mapcat #(if (coll? %) % [%]) (vals m))))

(defn- import-intent
  "A bank line the world imported: re-imported in the parent, unmatched —
   a match of it is replayed as its own intent."
  [world-db e]
  (let [line (d/pull world-db '[*] e)]
    {:intent/id (str "bank-line:" (:kontor.bank-line/external-id line))
     :kind :import
     :footprint #{}
     :effective-date (:kontor.bank-line/date line)
     :line (assoc (plain line #{:kontor.bank-line/status :kontor.bank-line/reconciled-at
                                :kontor.bank-line/posting})
                  :kontor.bank-line/status :unmatched)}))

(defn- match-intent
  "A bank line the world matched, as the match decision itself: the replay
   re-runs `kontor.banking.reconciliation/commit-match-tx-data` in the
   parent, which re-derives the payment, its applications and the settled
   invoices' statuses against the parent's state."
  [base-db world-db e]
  (let [line (d/pull world-db [:kontor.bank-line/external-id :kontor.bank-line/date
                               {:kontor.bank-line/source-account [:db/id]}
                               {:kontor.bank-line/posting [{:kontor.posting/transaction [:db/id]}]}]
                     e)
        pay (get-in line [:kontor.bank-line/posting :kontor.posting/transaction :db/id])
        t (d/pull world-db '[*] pay)
        bank (get-in line [:kontor.bank-line/source-account :db/id])
        contra (some (fn [p] (let [a (ref-id (:account p))] (when (not= a bank) a)))
                     (book/entry-postings world-db pay))
        applied-by (d/q '[:find ?u . :in $ ?p
                          :where [?a :kontor.payment-application/payment ?p]
                          [?a :kontor.payment-application/applied-by-uid ?u]]
                        world-db pay)
        settles (mapv (fn [s]
                        (let [s (ref-id s)]
                          (if (existed? base-db s)
                            {:eid s}
                            {:origin (:kontor.transaction/origin-id (d/entity world-db s))})))
                      (:kontor.transaction/settles t))]
    {::settled (mapv ref-id (:kontor.transaction/settles t))
     :intent/id (str "match:" (:kontor.bank-line/external-id line))
     :kind :match
     :footprint #{[:bank-line (:kontor.bank-line/external-id line)]
                  [:external-id (:kontor.transaction/external-id t)]}
     :effective-date (:kontor.bank-line/date line)
     :line-id (:kontor.bank-line/external-id line)
     :payment-id (:kontor.transaction/external-id t)
     :payment-origin (:kontor.transaction/origin-id t)
     :journal (ref-id (:kontor.transaction/journal t))
     :contra contra
     :settles settles
     :applied-by applied-by
     ::payment-eid pay}))

(defn- catalog-intent [world-db e]
  (let [[a v :as identity] (catalog-identity world-db e)]
    {:intent/id (str "catalog:" a "=" v)
     :kind :catalog
     :footprint #{}
     ;; first: everything else may refer to it
     :effective-date (java.util.Date. 0)
     :identity identity
     :entity (plain (d/pull world-db '[*] e) #{})}))

(defn- ref-attr? [db a]
  (= :db.type/ref (get-in (d/schema db) [a :db/valueType])))

(defn- translator
  "How an entity id of the world is named in the parent: an entity the
   world created as reference data by its identity (a lookup ref), a
   transaction it created by the tempid its replay gets, anything else (an
   entity of the base) as it is."
  [world-db catalog txs]
  (let [m (merge (into {} (map (fn [e] [e (catalog-identity world-db e)])) catalog)
                 (into {} (map (fn [e] [e (str "settle-" (:kontor.transaction/origin-id
                                                          (d/entity world-db e)))]))
                       txs))]
    (fn [x] (if (integer? x) (get m x x) x))))

(defn- translate-map
  "`m` (an entity map) with the entity ids in its ref attributes translated."
  [world-db tr m]
  (into {} (map (fn [[k v]]
                  [k (if (ref-attr? world-db k)
                       (if (coll? v) (mapv tr v) (tr v))
                       v)]))
        m))

(defn- update-some [m k f] (if (some? (get m k)) (update m k f) m))

(defn- translate
  [world-db tr {:keys [kind] :as i}]
  (case kind
    :entry
    (update i :entry
            (fn [en]
              (-> en
                  (update :journal tr)
                  (update-some :partner tr)
                  (update-some :settles #(mapv tr %))
                  (update :postings
                          (fn [ps]
                            (mapv (fn [p]
                                    (reduce #(update-some %1 %2 tr)
                                            (update-some p :analytic-distributions
                                                         (fn [ds] (mapv #(-> % (update-some :plan tr)
                                                                             (update-some :account tr))
                                                                        ds)))
                                            [:account :commodity :partner :entity :ledger]))
                                  ps))))))
    :invoice (-> i
                 (update :invoice #(translate-map world-db tr %))
                 (update :lines (fn [ls] (mapv #(translate-map world-db tr %) ls))))
    :import (update i :line #(translate-map world-db tr %))
    :match (-> i (update :journal tr) (update :contra tr) (update :applied-by tr))
    :catalog (update i :entity #(translate-map world-db tr %))
    :period (update-some i :sealed-by tr)
    :outbox i))

(defn- period-intent
  "A period the world closed or sealed, as that decision: re-run in the
   parent last, against its state — its own pre-close checks, its own
   sealing order. A period the parent already closed (sealed) is left as it
   is: both decided the same."
  [base-db world-db e]
  (let [w (d/pull world-db [:kontor.period/locked-at :kontor.period/sealed-at
                            {:kontor.period/sealed-by [:db/id]}]
                  e)
        b (d/pull base-db [:kontor.period/locked-at :kontor.period/sealed-at] e)]
    {:intent/id (str "period:" e)
     :kind :period
     :footprint #{[:period e]}
     :effective-date (or (:kontor.period/sealed-at w) (:kontor.period/locked-at w))
     :period e
     :close-at (when (and (:kontor.period/locked-at w) (not (:kontor.period/locked-at b)))
                 (:kontor.period/locked-at w))
     :seal-at (when (and (:kontor.period/sealed-at w) (not (:kontor.period/sealed-at b)))
                (:kontor.period/sealed-at w))
     :sealed-by (ref-id (:kontor.period/sealed-by w))}))

(defn- outbox-intent
  "An external effect the world queued and did not run: queued in the
   parent, last, its payload rebased onto the parent's numbers."
  [world-db e]
  (let [row (d/pull world-db [:kontor.side-effect-intent/key :kontor.side-effect-intent/type
                              :kontor.side-effect-intent/payload :kontor.side-effect-intent/created-at
                              :kontor.side-effect-intent/max-retries]
                    e)]
    {:intent/id (str "outbox:" (:kontor.side-effect-intent/key row))
     :kind :outbox
     :footprint #{[:outbox (:kontor.side-effect-intent/key row)]}
     :effective-date (:kontor.side-effect-intent/created-at row)
     :row row}))

(defn rebase
  "`s` with every world number in `renumber` ({world parent}) replaced by
   the parent's — longest first, so no number is clobbered by a prefix of
   another."
  [s renumber]
  (if (and (string? s) (seq renumber))
    (reduce (fn [acc [w p]] (str/replace acc w p))
            s
            (sort-by (comp - count key) renumber))
    s))

(declare referenced-entry-eids)

(defn- referenced-eids
  "Every entity id an intent refers to."
  [{:keys [kind entry reverses invoice lines line journal contra applied-by settles]}]
  (case kind
    :invoice (distinct (concat (remove #{(:kontor.invoice/issue-date invoice)} (ref-values invoice))
                               (mapcat ref-values lines)))
    :import (ref-values (dissoc line :kontor.bank-line/amount :kontor.bank-line/date
                                :kontor.bank-line/value-date))
    :match (remove nil? (concat [journal contra applied-by] (keep :eid settles)))
    :period []
    :outbox []
    :catalog []
    (referenced-entry-eids entry reverses)))

(defn- referenced-entry-eids
  [entry reverses]
  (->> (concat [(:journal entry) (:partner entry) reverses]
               (:settles entry)
               (mapcat (fn [p] (concat [(:account p) (:commodity p) (:partner p)
                                        (:entity p) (:ledger p)]
                                       (keep :plan (:analytic-distributions p))
                                       (keep :account (:analytic-distributions p))))
                       (:postings entry)))
       (filter integer?)
       distinct))

(defn extract
  "The world's net effect since its base, as intents (see the namespace):
   every entry it posted, except an entry it reversed itself — which is
   dropped together with its reversal. Throws `::unsupported` for anything
   else it changed, and `::new-reference` when an entry refers to an entity
   the world created (this slice replays against the base's entities)."
  [base-db world-db]
  (let [grouped (check-changes! base-db world-db (changed-entities base-db world-db))
        lines (ids-of grouped :bank-lines)
        matched (filterv (fn [e]
                           (and (= :reconciled (:kontor.bank-line/status (d/entity world-db e)))
                                (not= :reconciled (:kontor.bank-line/status (d/entity base-db e)))))
                         lines)
        matches (mapv #(match-intent base-db world-db %) matched)
        payments (set (map ::payment-eid matches))
        settled-invoices (set (d/q '[:find [?i ...] :in $ [?t ...]
                                     :where [?i :kontor.invoice/transaction ?t]]
                                   world-db (vec (mapcat ::settled matches))))
        _ (doseq [i (ids-of grouped :invoices)
                  :when (and (= :paid (:kontor.invoice/status (d/entity world-db i)))
                             (not (contains? settled-invoices i)))]
            (unsupported! "holds a paid invoice no match of it settles" {:entity i}))
        _ (doseq [i (ids-of grouped :invoice-statuses)
                  :when (not (contains? settled-invoices i))]
            (unsupported! "changed the status of an invoice no match of it settles" {:entity i}))
        txs (remove payments (ids-of grouped :transactions))
        intents (mapv #(intent world-db %) txs)
        in-world (set txs)
        self-reversed (set (mapcat (fn [{:keys [reverses] :as i}]
                                     (when (contains? in-world reverses)
                                       [reverses (::world-eid i)]))
                                   intents))
        catalog (ids-of grouped :catalog)
        tr (translator world-db catalog txs)
        kept (concat (map #(catalog-intent world-db %) catalog)
                     (remove #(contains? self-reversed (::world-eid %)) intents)
                     (map #(invoice-intent world-db %) (ids-of grouped :invoices))
                     (map #(import-intent world-db %) (remove #(existed? base-db %) lines))
                     matches
                     (map #(period-intent base-db world-db %) (ids-of grouped :periods))
                     (map #(outbox-intent world-db %) (ids-of grouped :outbox)))
        translated (mapv #(translate world-db tr %) kept)]
    (doseq [i translated
            e (referenced-eids i)
            :when (not (existed? base-db e))]
      (throw (ex-info "kontor.settlement: an intent refers to an entity the world created and this settlement cannot name"
                      {:type ::new-reference :entity e :intent (:intent/id i)})))
    (vec (sort-by (juxt :effective-date #(str (:intent/id %))) translated))))

(defn parent-claims
  "The footprint keys the parent claimed since `base-db`: its own entries'
   origins, caller ids and the base entries it reversed. Unlike [[extract]]
   this reads whatever the parent did and refuses nothing."
  [base-db parent-db]
  (let [since (:max-tx base-db)
        txs (d/q '[:find [?t ...] :in $ ?since
                   :where [?t :kontor.transaction/posted-at _ ?tx] [(> ?tx ?since)]]
                 parent-db since)
        invoices (d/q '[:find [?x ...] :in $ ?since
                        :where [?i :kontor.invoice/external-id ?x ?tx] [(> ?tx ?since)]]
                      parent-db since)]
    (into (into (set (map (fn [x] [:invoice x]) invoices))
                (map (fn [x] [:bank-line x]))
                (d/q '[:find [?x ...] :in $ ?since
                       :where [?l :kontor.bank-line/status :reconciled ?tx] [(> ?tx ?since)]
                       [?l :kontor.bank-line/external-id ?x]]
                     parent-db since))
          (mapcat (fn [e]
                    (let [t (d/pull parent-db '[*] e)
                          caller-id (when-not (world-number parent-db t)
                                      (:kontor.transaction/external-id t))]
                      (cond-> []
                        (:kontor.transaction/origin-id t) (conj [:origin (:kontor.transaction/origin-id t)])
                        caller-id (conj [:external-id caller-id])
                        (:kontor.transaction/reverses t)
                        (conj [:reverses (ref-id (:kontor.transaction/reverses t))])))))
          txs)))

;; ============================================================================
;; Stamping into the parent
;; ============================================================================

(defn- invoice-tx-data
  "Re-create an invoice the world created, as a draft, and — when the world
   sent it — link it to its replayed posting (the gate then numbers it) and
   record the draft → sent transition."
  [db {:keys [invoice lines status transaction-origin]}]
  (let [ext (:kontor.invoice/external-id invoice)]
    (when-not (d/entity db [:kontor.invoice/external-id ext])
      (let [created (invoice/create-tx-data db (assoc invoice :kontor.invoice/lines lines))
            tempid (str "invoice-" ext)]
        (if (= :sent status)
          (-> created
              (conj {:db/id tempid :kontor.invoice/transaction (str "settle-" transaction-origin)})
              (into (sm/record-status-change-tx-data
                     db {:entity tempid :entity-type :invoice
                         :facet :kontor.invoice/status :from :draft :to :sent})))
          created)))))

(defn stamp-tx-data
  "Pure-over-`db` tx-data that re-posts `intents` (in order) into the book
   `db` belongs to, skipping those whose origin it already holds. Each
   entry keeps its origin; the gate allocates its number."
  [db intents]
  (vec
   (mapcat
    (fn [{:intent/keys [id] :keys [kind entry reverses actor] :as i}]
      (case kind
        :invoice (invoice-tx-data db i)
        (:import :match :catalog :period :outbox) nil
        (when-not (d/entity db [:kontor.transaction/origin-id id])
          (let [tempid (str "settle-" id)
                input (assoc (build/build-input entry) :tx-tempid tempid)
                tx-data (posting-build/post-transaction-tx-data
                         input (cond-> {} actor (assoc :actor actor)))]
            (mapv (fn [form]
                    (if (and (map? form) (= tempid (:db/id form)))
                      (cond-> (assoc form :kontor.transaction/origin-id id)
                        reverses (assoc :kontor.transaction/reverses reverses))
                      form))
                  tx-data)))))
    intents)))

(defn- entid
  "The entity id `x` names in `db` — an id, or a lookup ref — or nil when
   nothing has that identity."
  [db x]
  (cond (integer? x) x
        (vector? x) (d/q '[:find ?e . :in $ ?a ?v :where [?e ?a ?v]] db (first x) (second x))
        :else nil))

(defn- same-as-parent!
  "Refuse when the parent already holds catalog entity `identity` with other
   attributes than the world gave it: two worlds' customers, say, under one
   id. The same attributes are the same entity."
  [db [a :as identity] entity]
  (let [eid (entid db identity)
        differs (for [[k wv] (dissoc entity a)
                      :let [pv (get (d/pull db [k] eid) k)
                            pv (if (ref-attr? db k)
                                 (if (sequential? pv) (set (map :db/id pv)) (:db/id pv))
                                 pv)
                            wv (if (ref-attr? db k)
                                 (if (and (sequential? wv) (not (keyword? (first wv)))) (set (map #(entid db %) wv)) (entid db wv))
                                 wv)]
                      :when (not= pv wv)]
                  {:attr k :world wv :parent pv})]
    (when (seq differs)
      (throw (ex-info (str "kontor.settlement: the parent holds " (pr-str identity)
                           " with other attributes than the world gave it")
                      {:type ::conflicting-entity :identity identity :differs (vec differs)})))))

(defn- phase-1-tx-data
  "The reference data the world created and the bank lines it imported,
   that the book does not hold yet. Within this transaction a new entity is
   named by its tempid; in the later ones by its identity."
  [db intents]
  (let [catalog (filter #(= :catalog (:kind %)) intents)
        fresh (remove (fn [{:keys [identity entity]}]
                        (when (entid db identity)
                          (same-as-parent! db identity entity)
                          true))
                      catalog)
        tempids (into {} (map (fn [{:keys [identity]}]
                                [identity (str "catalog-" (first identity) "=" (second identity))]))
                      fresh)
        name-of (fn [x] (get tempids x x))
        named (fn [m] (into {} (map (fn [[k v]]
                                      [k (if (ref-attr? db k)
                                           (if (sequential? v)
                                             (if (vector? (first v)) (mapv name-of v) (name-of v))
                                             v)
                                           v)]))
                            m))]
    (vec (concat
          (for [{:keys [identity entity]} fresh]
            (assoc (named entity) :db/id (tempids identity)))
          (for [{:keys [kind line]} intents
                :when (and (= :import kind)
                           (not (d/entity db [:kontor.bank-line/external-id
                                              (:kontor.bank-line/external-id line)])))]
            (named line))))))

(defn- match-tx-data
  "The replayed match `m` against `db`, or nil when the book already holds
   its payment (by the world payment's origin). A line the book has
   meanwhile matched otherwise is refused by `commit-match-tx-data`
   (`:reconciliation/already-matched`)."
  [db {:keys [line-id payment-origin journal contra settles applied-by]}]
  (when-not (d/entity db [:kontor.transaction/origin-id payment-origin])
    (let [line (:db/id (d/entity db [:kontor.bank-line/external-id line-id]))
          settled (mapv (fn [{:keys [eid origin]}]
                          (or eid (:db/id (d/entity db [:kontor.transaction/origin-id origin]))))
                        settles)]
      (mapv (fn [form]
              (if (and (map? form) (= "pay-tx" (:db/id form)))
                (assoc form :kontor.transaction/origin-id payment-origin)
                form))
            (recon/commit-match-tx-data
             db line
             (if (seq settled) {:kind :settle :transactions settled} {:kind :categorize :contra-account contra})
             journal
             (cond-> {:contra-account contra}
               applied-by (assoc :applied-by-uid applied-by)))))))

(defn stamp!
  "Re-post `intents` into `conn`'s book through the gate, in three steps:
   the reference data the world created (partners, accounts, … — one the
   parent already holds with other attributes refuses the settlement,
   `::conflicting-entity`) and the bank lines it imported; its entries and
   invoices, as ONE
   transaction — the parent numbers them consecutively, and a refused
   intent (a locked period, a closed sequence bucket) refuses them all; then
   its bank matches, each re-run against the parent's state. Every step
   skips what the book already holds (lines by id, entries by origin,
   matches by payment), so a retry after a failure books nothing twice.
   Returns {world-number parent-number} for what carried a rendered number
   in the world."
  [conn intents]
  (let [phase-1 (phase-1-tx-data (d/db conn) intents)]
    (when (seq phase-1)
      (gate/transact-with-validation conn phase-1)))
  (let [tx-data (stamp-tx-data (d/db conn) intents)]
    (when (seq tx-data)
      (gate/transact-with-validation conn tx-data)))
  (doseq [m intents
          :when (= :match (:kind m))
          :let [tx-data (match-tx-data (d/db conn) m)]
          :when tx-data]
    (gate/transact-with-validation conn tx-data))
  (doseq [{:keys [period close-at seal-at sealed-by]} (sort-by :effective-date
                                                               (filter #(= :period (:kind %)) intents))]
    (let [locked? #(:kontor.period/locked-at (d/entity (d/db conn) period))]
      (when (and close-at (not (locked?)))
        (period/close! conn period {:at close-at}))
      (when (and seal-at (not (:kontor.period/sealed-at (d/entity (d/db conn) period))))
        (gate/transact-with-validation
         conn (period/seal-tx-data (d/db conn) period
                                   (cond-> {:at seal-at} sealed-by (assoc :sealed-by sealed-by)))))))
  (let [db (d/db conn)
        renumber (into {}
                       (keep (fn [{:intent/keys [id] :keys [kind world-number invoice]}]
                               (when world-number
                                 [world-number
                                  (if (= :invoice kind)
                                    (:kontor.invoice/number
                                     (d/entity db [:kontor.invoice/external-id (:kontor.invoice/external-id invoice)]))
                                    (:kontor.transaction/external-id
                                     (d/entity db [:kontor.transaction/origin-id id])))])))
                       intents)
        outbox (vec (for [{:keys [kind row]} intents
                          :when (and (= :outbox kind)
                                     (not (entid db [:kontor.side-effect-intent/key
                                                     (:kontor.side-effect-intent/key row)])))]
                      (-> row
                          (update-some :kontor.side-effect-intent/payload #(rebase % renumber))
                          (assoc :kontor.side-effect-intent/status :pending))))]
    (when (seq outbox)
      (gate/transact-with-validation conn outbox))
    renumber))
