(ns kontor.settlement
  "A book that lived in a speculative world settles into its parent by
   replay, never by datom merge (ADR-172).

   A world — a branch of the book an agent works in — is an autonomous book:
   it posts, numbers and reverses as the root does. When the parent takes it
   in, [[extract]] reads the world's NET effect since its base as intents,
   [[parent-claims]] what the parent did meanwhile, and [[stamp!]] re-posts
   the intents through the gate in the parent, which allocates fresh gapless
   numbers. Conflicts between worlds, or between a world and its parent, are
   decided by the caller (footprints), never by picking datoms.

   An intent:

     {:intent/id      origin uuid (`:kontor.transaction/origin-id`)
      :footprint      #{[:origin id] [:external-id caller-id] [:reverses eid] …}
      :effective-date inst
      :entry          `kontor.book` entry options that re-create the entry
      :reverses       eid of a base entry it reverses, or nil
      :actor          uid of who sealed it, or nil
      :world-number   the number it carried in the world, or nil}

   Replayed: posted journal entries (any `kontor.book` verb), reversals, and
   invoices the world created — as drafts, or sent, in which case the replay
   links them to their replayed posting and the gate gives them the parent's
   gapless `:kontor.invoice/number` (an invoice intent's footprint is
   `[:invoice external-id]`). Anything else a world changed — a draft entry,
   a new partner or account, an invoice paid or cancelled, a period close —
   is refused by [[extract]] with the entities named: silently carrying it
   over as datoms is exactly what this namespace exists to prevent."
  (:require [datahike.api :as d]
            [kontor.book :as book]
            [kontor.book.build :as build]
            [kontor.banking.reconciliation :as recon]
            [kontor.document.invoice :as invoice]
            [kontor.workflow.status-machine :as sm]
            [kontor.gate :as gate]
            [kontor.numbering :as numbering]
            [kontor.posting.build :as posting-build]))

;; ============================================================================
;; What a world changed
;; ============================================================================

(defn- world-datoms
  "Datoms `world-db` holds that `base-db` did not: those of transactions
   after the base's last one (a branch continues the base's history)."
  [base-db world-db]
  (let [since (:max-tx base-db)]
    (filter #(> (:tx %) since) (d/datoms world-db :eavt))))

(def ^:private carried-transaction-attrs
  "Transaction attributes a replay re-creates from the entry, or that the
   gate regenerates in the parent."
  #{:kontor.transaction/journal :kontor.transaction/effective-date
    :kontor.transaction/narration :kontor.transaction/partner
    :kontor.transaction/external-id :kontor.transaction/settles
    :kontor.transaction/reverses :kontor.transaction/origin-id
    ;; regenerated by the seal and the gate
    :kontor.transaction/state :kontor.transaction/posted-at
    :kontor.transaction/posted-by :kontor.transaction/sequence-number
    :kontor.transaction/sequence-key
    :kontor.audit/create-uid :kontor.audit/write-uid})

(def ^:private carried-posting-attrs
  "Posting attributes `kontor.book/entry-postings` re-creates."
  #{:kontor.posting/transaction :kontor.posting/posted-at
    :kontor.posting/account :kontor.posting/amount :kontor.posting/commodity
    :kontor.posting/partner :kontor.posting/entity :kontor.posting/ledger
    :kontor.posting/narration :kontor.posting/display-type
    :kontor.posting/period-tag :kontor.posting/dimensions
    :kontor.posting/analytic-distributions
    :kontor.audit/create-uid :kontor.audit/write-uid})

(defn- valid-time-attr? [a] (= "db.valid" (namespace a)))

(defn- entity-kind
  "What entity `e` is, from the attributes it has in `db`."
  [db e]
  (let [attrs (set (map :a (d/datoms db :eavt e)))
        has (fn [ns] (some #(= ns (namespace %)) attrs))]
    (cond
      (contains? attrs :kontor.transaction/journal) :transaction
      (contains? attrs :kontor.invoice/external-id) :invoice
      (contains? attrs :kontor.bank-line/external-id) :bank-line
      (has "kontor.payment-application") :payment-application
      (has "kontor.invoice-line") :invoice-line
      (has "kontor.status-history") :status-history
      (contains? attrs :kontor.posting/transaction) :posting
      (has "kontor.posting-dimension") :posting-part
      (has "kontor.analytic-distribution") :posting-part
      (has "kontor.actor") :actor
      (contains? attrs :kontor.journal/code) :journal
      :else :other)))

(defn- existed? [db e] (boolean (seq (d/datoms db :eavt e))))

(defn- unsupported! [what details]
  (throw (ex-info (str "kontor.settlement: the world " what
                       " — this settlement cannot replay it, and carrying it"
                       " over as datoms would bypass the gate (ADR-172)")
                  (merge {:type ::unsupported} details))))

(defn- changed-entities
  "{eid #{attr}} of what the world changed, tx entities left out."
  [base-db world-db]
  (reduce (fn [m {:keys [e a tx]}]
            (if (or (= e tx) (= "db" (namespace a)))
              m
              (update m e (fnil conj #{}) a)))
          {}
          (world-datoms base-db world-db)))

(def ^:private replayed-invoice-statuses
  "`:paid` only when a replayed match settles it: the invoice replays as
   sent, and the match re-derives its status in the parent."
  #{:draft :sent :paid})

(defn- check-changes!
  "Refuse any change this slice does not replay. Returns {:transactions
   [eid] :invoices [eid]}, the new ones."
  [base-db world-db changes]
  (let [counter-attrs #{:kontor.journal/last-sequence :kontor.journal/last-sequence-key}]
    (group-by first
              (keep
               (fn [[e attrs]]
                 (let [kind (entity-kind world-db e)
                       new? (not (existed? base-db e))
                       attrs (remove valid-time-attr? attrs)]
                   (case kind
                     :transaction
                     (let [unknown (remove carried-transaction-attrs attrs)
                           t (d/pull world-db [:kontor.transaction/posted-at] e)]
                       (cond
                         (not new?) (unsupported! "changed an entry of its base" {:entity e :attrs (vec attrs)})
                         (seq unknown) (unsupported! "wrote transaction attributes a replay does not carry"
                                                     {:entity e :attrs (vec unknown)})
                         (not (:kontor.transaction/posted-at t)) (unsupported! "holds a draft entry" {:entity e})
                         :else [:transactions e]))
                     :invoice
                     (let [status (:kontor.invoice/status (d/pull world-db [:kontor.invoice/status] e))]
                       (cond
                         ;; a match settling it re-derives its status in the
                         ;; parent; anything else is checked in `extract`
                         (and (not new?) (every? #{:kontor.invoice/status} attrs))
                         [:invoice-statuses e]
                         (not new?) (unsupported! "changed an invoice of its base" {:entity e :attrs (vec attrs)})
                         (not (replayed-invoice-statuses status))
                         (unsupported! "holds an invoice in a status this settlement cannot replay"
                                       {:entity e :status status})
                         :else [:invoices e]))
                     :bank-line
                     (if (or new? (every? #{:kontor.bank-line/status :kontor.bank-line/reconciled-at
                                            :kontor.bank-line/posting}
                                          attrs))
                       [:bank-lines e]
                       (unsupported! "changed a bank line beyond matching it" {:entity e :attrs (vec attrs)}))
                     ;; regenerated when the match is replayed
                     :payment-application
                     (when-not new? (unsupported! "changed a payment application" {:entity e}))
                     :invoice-line (when-not new? (unsupported! "changed an invoice line of its base" {:entity e :attrs (vec attrs)}))
            ;; regenerated by the replay's own status changes
                     :status-history (when-not new? (unsupported! "changed a status history row" {:entity e}))
                     :posting
                     (let [unknown (remove carried-posting-attrs attrs)]
                       (when (or (not new?) (seq unknown))
                         (unsupported! "wrote posting attributes a replay does not carry"
                                       {:entity e :attrs (vec (if new? unknown attrs))}))
                       nil)
                     (:posting-part :actor) (when-not new? (unsupported! "changed an existing entity" {:entity e :kind kind :attrs (vec attrs)}))
                     :journal (when (seq (remove counter-attrs attrs))
                                (unsupported! "changed a journal" {:entity e :attrs (vec attrs)}))
                     (unsupported! "changed an entity of a kind it cannot replay"
                                   {:entity e :kind kind :attrs (vec attrs)}))))
               changes))))

(defn- ids-of [grouped k] (mapv second (get grouped k)))

;; ============================================================================
;; Intents
;; ============================================================================

(defn- ref-id [x] (if (map? x) (:db/id x) x))

(defn- world-number
  "The number the numbering rendered for entry `t` in the world, or nil when
   its external-id is the caller's own."
  [db {:kontor.transaction/keys [external-id sequence-number journal effective-date]}]
  (when (and external-id sequence-number)
    (let [cfg (numbering/journal-config db (ref-id journal))]
      (when (= external-id (numbering/render cfg sequence-number effective-date))
        external-id))))

(defn- intent
  [world-db e]
  (let [t (d/pull world-db '[* {:kontor.transaction/posted-by [:kontor.actor/uid]}] e)
        rendered (world-number world-db t)
        caller-id (when-not rendered (:kontor.transaction/external-id t))
        reverses (ref-id (:kontor.transaction/reverses t))
        entry (cond-> {:journal (ref-id (:kontor.transaction/journal t))
                       :effective-date (:kontor.transaction/effective-date t)
                       :postings (book/entry-postings world-db e)}
                (:kontor.transaction/narration t) (assoc :narration (:kontor.transaction/narration t))
                (:kontor.transaction/partner t) (assoc :partner (ref-id (:kontor.transaction/partner t)))
                caller-id (assoc :external-id caller-id)
                (seq (:kontor.transaction/settles t))
                (assoc :settles (mapv ref-id (:kontor.transaction/settles t))))
        origin (:kontor.transaction/origin-id t)]
    {:intent/id origin
     :kind :entry
     :footprint (cond-> #{[:origin origin]}
                  caller-id (conj [:external-id caller-id])
                  reverses (conj [:reverses reverses]))
     :effective-date (:kontor.transaction/effective-date t)
     :entry entry
     :reverses reverses
     :actor (get-in t [:kontor.transaction/posted-by :kontor.actor/uid])
     :world-number rendered
     ::world-eid e}))

(defn- plain
  "A pulled entity as data for re-creation: refs as eids, without the
   attributes in `drop`."
  [m drop]
  (into {} (keep (fn [[k v]]
                   (when-not (contains? drop k)
                     [k (cond (map? v) (:db/id v)
                              (and (coll? v) (map? (first v))) (mapv :db/id v)
                              :else v)])))
        (dissoc m :db/id)))

(defn- invoice-intent
  [world-db e]
  (let [inv (d/pull world-db '[* {:kontor.invoice/lines [*]}] e)
        ext (:kontor.invoice/external-id inv)
        origin (some->> (:kontor.invoice/transaction inv) ref-id
                        (d/entity world-db) :kontor.transaction/origin-id)]
    {:intent/id (str "invoice:" ext)
     :kind :invoice
     :footprint #{[:invoice ext]}
     :effective-date (:kontor.invoice/issue-date inv)
     :invoice (plain inv #{:kontor.invoice/lines :kontor.invoice/transaction
                           :kontor.invoice/status :kontor.invoice/number})
     :lines (mapv #(plain % #{:kontor.invoice-line/invoice})
                  (sort-by :kontor.invoice-line/sequence (:kontor.invoice/lines inv)))
     ;; a paid one replays as sent: its match re-derives the rest
     :status (if (= :paid (:kontor.invoice/status inv)) :sent (:kontor.invoice/status inv))
     :transaction-origin origin
     :world-number (:kontor.invoice/number inv)}))

(defn- ref-values [m] (filter integer? (mapcat #(if (coll? %) % [%]) (vals m))))

(defn- import-intent
  "A bank line the world imported: re-imported in the parent, unmatched —
   a match of it is replayed as its own intent."
  [world-db e]
  (let [line (d/pull world-db '[*] e)]
    {:intent/id (str "bank-line:" (:kontor.bank-line/external-id line))
     :kind :import
     :footprint #{}
     :effective-date (:kontor.bank-line/date line)
     :line (assoc (plain line #{:kontor.bank-line/status :kontor.bank-line/reconciled-at
                                :kontor.bank-line/posting})
                  :kontor.bank-line/status :unmatched)}))

(defn- match-intent
  "A bank line the world matched, as the match decision itself: the replay
   re-runs `kontor.banking.reconciliation/commit-match-tx-data` in the
   parent, which re-derives the payment, its applications and the settled
   invoices' statuses against the parent's state."
  [base-db world-db e]
  (let [line (d/pull world-db [:kontor.bank-line/external-id :kontor.bank-line/date
                               {:kontor.bank-line/source-account [:db/id]}
                               {:kontor.bank-line/posting [{:kontor.posting/transaction [:db/id]}]}]
                     e)
        pay (get-in line [:kontor.bank-line/posting :kontor.posting/transaction :db/id])
        t (d/pull world-db '[*] pay)
        bank (get-in line [:kontor.bank-line/source-account :db/id])
        contra (some (fn [p] (let [a (ref-id (:account p))] (when (not= a bank) a)))
                     (book/entry-postings world-db pay))
        applied-by (d/q '[:find ?u . :in $ ?p
                          :where [?a :kontor.payment-application/payment ?p]
                          [?a :kontor.payment-application/applied-by-uid ?u]]
                        world-db pay)
        settles (mapv (fn [s]
                        (let [s (ref-id s)]
                          (if (existed? base-db s)
                            {:eid s}
                            {:origin (:kontor.transaction/origin-id (d/entity world-db s))})))
                      (:kontor.transaction/settles t))]
    {::settled (mapv ref-id (:kontor.transaction/settles t))
     :intent/id (str "match:" (:kontor.bank-line/external-id line))
     :kind :match
     :footprint #{[:bank-line (:kontor.bank-line/external-id line)]
                  [:external-id (:kontor.transaction/external-id t)]}
     :effective-date (:kontor.bank-line/date line)
     :line-id (:kontor.bank-line/external-id line)
     :payment-id (:kontor.transaction/external-id t)
     :payment-origin (:kontor.transaction/origin-id t)
     :journal (ref-id (:kontor.transaction/journal t))
     :contra contra
     :settles settles
     :applied-by applied-by
     ::payment-eid pay}))

(declare referenced-entry-eids)

(defn- referenced-eids
  "Every entity id an intent refers to."
  [{:keys [kind entry reverses invoice lines line journal contra applied-by settles]}]
  (case kind
    :invoice (distinct (concat (remove #{(:kontor.invoice/issue-date invoice)} (ref-values invoice))
                               (mapcat ref-values lines)))
    :import (ref-values (dissoc line :kontor.bank-line/amount :kontor.bank-line/date
                                :kontor.bank-line/value-date))
    :match (remove nil? (concat [journal contra applied-by] (keep :eid settles)))
    (referenced-entry-eids entry reverses)))

(defn- referenced-entry-eids
  [entry reverses]
  (->> (concat [(:journal entry) (:partner entry) reverses]
               (:settles entry)
               (mapcat (fn [p] (concat [(:account p) (:commodity p) (:partner p)
                                        (:entity p) (:ledger p)]
                                       (keep :plan (:analytic-distributions p))
                                       (keep :account (:analytic-distributions p))))
                       (:postings entry)))
       (filter integer?)
       distinct))

(defn extract
  "The world's net effect since its base, as intents (see the namespace):
   every entry it posted, except an entry it reversed itself — which is
   dropped together with its reversal. Throws `::unsupported` for anything
   else it changed, and `::new-reference` when an entry refers to an entity
   the world created (this slice replays against the base's entities)."
  [base-db world-db]
  (let [grouped (check-changes! base-db world-db (changed-entities base-db world-db))
        lines (ids-of grouped :bank-lines)
        matched (filterv (fn [e]
                           (and (= :reconciled (:kontor.bank-line/status (d/entity world-db e)))
                                (not= :reconciled (:kontor.bank-line/status (d/entity base-db e)))))
                         lines)
        matches (mapv #(match-intent base-db world-db %) matched)
        payments (set (map ::payment-eid matches))
        settled-invoices (set (d/q '[:find [?i ...] :in $ [?t ...]
                                     :where [?i :kontor.invoice/transaction ?t]]
                                   world-db (vec (mapcat ::settled matches))))
        _ (doseq [i (ids-of grouped :invoices)
                  :when (and (= :paid (:kontor.invoice/status (d/entity world-db i)))
                             (not (contains? settled-invoices i)))]
            (unsupported! "holds a paid invoice no match of it settles" {:entity i}))
        _ (doseq [i (ids-of grouped :invoice-statuses)
                  :when (not (contains? settled-invoices i))]
            (unsupported! "changed the status of an invoice no match of it settles" {:entity i}))
        txs (remove payments (ids-of grouped :transactions))
        intents (mapv #(intent world-db %) txs)
        in-world (set txs)
        self-reversed (set (mapcat (fn [{:keys [reverses] :as i}]
                                     (when (contains? in-world reverses)
                                       [reverses (::world-eid i)]))
                                   intents))
        kept (concat (remove #(contains? self-reversed (::world-eid %)) intents)
                     (map #(invoice-intent world-db %) (ids-of grouped :invoices))
                     (map #(import-intent world-db %) (remove #(existed? base-db %) lines))
                     matches)]
    (doseq [i kept
            e (referenced-eids i)
            :when (not (existed? base-db e))]
      (throw (ex-info "kontor.settlement: an entry refers to an entity the world created"
                      {:type ::new-reference :entity e :intent (:intent/id i)})))
    (vec (sort-by (juxt :effective-date #(str (:intent/id %))) kept))))

(defn parent-claims
  "The footprint keys the parent claimed since `base-db`: its own entries'
   origins, caller ids and the base entries it reversed. Unlike [[extract]]
   this reads whatever the parent did and refuses nothing."
  [base-db parent-db]
  (let [since (:max-tx base-db)
        txs (d/q '[:find [?t ...] :in $ ?since
                   :where [?t :kontor.transaction/posted-at _ ?tx] [(> ?tx ?since)]]
                 parent-db since)
        invoices (d/q '[:find [?x ...] :in $ ?since
                        :where [?i :kontor.invoice/external-id ?x ?tx] [(> ?tx ?since)]]
                      parent-db since)]
    (into (into (set (map (fn [x] [:invoice x]) invoices))
                (map (fn [x] [:bank-line x]))
                (d/q '[:find [?x ...] :in $ ?since
                       :where [?l :kontor.bank-line/status :reconciled ?tx] [(> ?tx ?since)]
                       [?l :kontor.bank-line/external-id ?x]]
                     parent-db since))
          (mapcat (fn [e]
                    (let [t (d/pull parent-db '[*] e)
                          caller-id (when-not (world-number parent-db t)
                                      (:kontor.transaction/external-id t))]
                      (cond-> []
                        (:kontor.transaction/origin-id t) (conj [:origin (:kontor.transaction/origin-id t)])
                        caller-id (conj [:external-id caller-id])
                        (:kontor.transaction/reverses t)
                        (conj [:reverses (ref-id (:kontor.transaction/reverses t))])))))
          txs)))

;; ============================================================================
;; Stamping into the parent
;; ============================================================================

(defn- invoice-tx-data
  "Re-create an invoice the world created, as a draft, and — when the world
   sent it — link it to its replayed posting (the gate then numbers it) and
   record the draft → sent transition."
  [db {:keys [invoice lines status transaction-origin]}]
  (let [ext (:kontor.invoice/external-id invoice)]
    (when-not (d/entity db [:kontor.invoice/external-id ext])
      (let [created (invoice/create-tx-data db (assoc invoice :kontor.invoice/lines lines))
            tempid (str "invoice-" ext)]
        (if (= :sent status)
          (-> created
              (conj {:db/id tempid :kontor.invoice/transaction (str "settle-" transaction-origin)})
              (into (sm/record-status-change-tx-data
                     db {:entity tempid :entity-type :invoice
                         :facet :kontor.invoice/status :from :draft :to :sent})))
          created)))))

(defn stamp-tx-data
  "Pure-over-`db` tx-data that re-posts `intents` (in order) into the book
   `db` belongs to, skipping those whose origin it already holds. Each
   entry keeps its origin; the gate allocates its number."
  [db intents]
  (vec
   (mapcat
    (fn [{:intent/keys [id] :keys [kind entry reverses actor] :as i}]
      (case kind
        :invoice (invoice-tx-data db i)
        (:import :match) nil
        (when-not (d/entity db [:kontor.transaction/origin-id id])
          (let [tempid (str "settle-" id)
                input (assoc (build/build-input entry) :tx-tempid tempid)
                tx-data (posting-build/post-transaction-tx-data
                         input (cond-> {} actor (assoc :actor actor)))]
            (mapv (fn [form]
                    (if (and (map? form) (= tempid (:db/id form)))
                      (cond-> (assoc form :kontor.transaction/origin-id id)
                        reverses (assoc :kontor.transaction/reverses reverses))
                      form))
                  tx-data)))))
    intents)))

(defn- import-tx-data
  "Bank lines the world imported that the book does not hold yet."
  [db intents]
  (vec (for [{:keys [kind line]} intents
             :when (and (= :import kind)
                        (not (d/entity db [:kontor.bank-line/external-id
                                           (:kontor.bank-line/external-id line)])))]
         line)))

(defn- match-tx-data
  "The replayed match `m` against `db`, or nil when the book already holds
   its payment (by the world payment's origin). A line the book has
   meanwhile matched otherwise is refused by `commit-match-tx-data`
   (`:reconciliation/already-matched`)."
  [db {:keys [line-id payment-origin journal contra settles applied-by]}]
  (when-not (d/entity db [:kontor.transaction/origin-id payment-origin])
    (let [line (:db/id (d/entity db [:kontor.bank-line/external-id line-id]))
          settled (mapv (fn [{:keys [eid origin]}]
                          (or eid (:db/id (d/entity db [:kontor.transaction/origin-id origin]))))
                        settles)]
      (mapv (fn [form]
              (if (and (map? form) (= "pay-tx" (:db/id form)))
                (assoc form :kontor.transaction/origin-id payment-origin)
                form))
            (recon/commit-match-tx-data
             db line
             (if (seq settled) {:kind :settle :transactions settled} {:kind :categorize :contra-account contra})
             journal
             (cond-> {:contra-account contra}
               applied-by (assoc :applied-by-uid applied-by)))))))

(defn stamp!
  "Re-post `intents` into `conn`'s book through the gate, in three steps:
   the bank lines the world imported; its entries and invoices, as ONE
   transaction — the parent numbers them consecutively, and a refused
   intent (a locked period, a closed sequence bucket) refuses them all; then
   its bank matches, each re-run against the parent's state. Every step
   skips what the book already holds (lines by id, entries by origin,
   matches by payment), so a retry after a failure books nothing twice.
   Returns {world-number parent-number} for what carried a rendered number
   in the world."
  [conn intents]
  (let [imports (import-tx-data (d/db conn) intents)]
    (when (seq imports)
      (gate/transact-with-validation conn imports)))
  (let [tx-data (stamp-tx-data (d/db conn) intents)]
    (when (seq tx-data)
      (gate/transact-with-validation conn tx-data)))
  (doseq [m intents
          :when (= :match (:kind m))
          :let [tx-data (match-tx-data (d/db conn) m)]
          :when tx-data]
    (gate/transact-with-validation conn tx-data))
  (let [db (d/db conn)]
    (into {}
          (keep (fn [{:intent/keys [id] :keys [kind world-number invoice]}]
                  (when world-number
                    [world-number
                     (if (= :invoice kind)
                       (:kontor.invoice/number
                        (d/entity db [:kontor.invoice/external-id (:kontor.invoice/external-id invoice)]))
                       (:kontor.transaction/external-id
                        (d/entity db [:kontor.transaction/origin-id id])))])))
          intents)))
